/* BlogAuth V1 tests/comments.test.js — Comments and Likes Integration Tests */
require('./setup');
const request = require('supertest');
const app = require('../app');
const { User, Article, Comment, Category } = require('../models');

describe('Comments and Likes Endpoints', () => {
  let token;
  let userId;
  let articleId;
  let categoryId;

  beforeAll(async () => {
    await User.deleteMany({});
    await Article.deleteMany({});
    await Comment.deleteMany({});
    await Category.deleteMany({});

    // Register user which returns tokens and data directly
    const regRes = await request(app)
      .post('/api/v1/auth/register')
      .send({
        username: 'commenter_tom',
        email: 'tom@example.com',
        password: 'Password123!'
      });

    token = regRes.body.token;
    userId = regRes.body.data.user.id;

    const cat = await Category.create({ name: 'News', slug: 'news' });
    categoryId = cat._id;

    // Create an article
    const art = await Article.create({
      title: 'Likes and Comments Article',
      slug: 'likes-and-comments-article',
      content: 'This is testing text body...',
      author: userId,
      category: categoryId,
      status: 'published'
    });
    articleId = art._id.toString();
  });

  it('should post a comment to an article', async () => {
    const res = await request(app)
      .post('/api/v1/comments')
      .set('Authorization', `Bearer ${token}`)
      .send({
        article: articleId,
        content: 'This comment was generated by supertest.'
      });

    expect(res.statusCode).toBe(201);
    expect(res.body.success).toBe(true);
    expect(res.body.data.comment.content).toBe('This comment was generated by supertest.');
  });

  it('should fetch comments of an article', async () => {
    const res = await request(app)
      .get(`/api/v1/comments/article/${articleId}`);

    expect(res.statusCode).toBe(200);
    expect(res.body.success).toBe(true);
    expect(res.body.data.comments.length).toBeGreaterThan(0);
  });

  it('should toggle liking an article', async () => {
    const res = await request(app)
      .post('/api/v1/likes')
      .set('Authorization', `Bearer ${token}`)
      .send({
        article: articleId
      });

    expect(res.statusCode).toBe(201);
    expect(res.body.success).toBe(true);
    expect(res.body.isLiked).toBe(true);
  });
});
