import { 
  FiSearch, 
  FiArrowRight, 
  FiArrowLeft, 
  FiCheck, 
  FiAlertCircle, 
  FiMenu, 
  FiX, 
  FiUser, 
  FiCalendar, 
  FiEdit, 
  FiTrash, 
  FiPlus, 
  FiLogOut, 
  FiLoader, 
  FiChevronDown, 
  FiChevronRight,
  FiBookOpen,
  FiLock,
  FiMail,
  FiTag,
  FiClock,
  FiExternalLink
} from 'react-icons/fi';

export const Icon = {
  Search: FiSearch,
  ArrowRight: FiArrowRight,
  ArrowLeft: FiArrowLeft,
  Check: FiCheck,
  AlertCircle: FiAlertCircle,
  Menu: FiMenu,
  X: FiX,
  User: FiUser,
  Calendar: FiCalendar,
  Edit: FiEdit,
  Trash: FiTrash,
  Plus: FiPlus,
  LogOut: FiLogOut,
  Loader: FiLoader,
  ChevronDown: FiChevronDown,
  ChevronRight: FiChevronRight,
  BookOpen: FiBookOpen,
  Lock: FiLock,
  Mail: FiMail,
  Tag: FiTag,
  Clock: FiClock,
  ExternalLink: FiExternalLink
};
